name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        ssh-passphrase: ${{ secrets.SSH_PASSWORD }}

    - name: Remove .git in htdocs on Server
      run: |
        ssh ${{ secrets.USER }}@${{ secrets.USER_SERVER }} "rm -rf /var/www/html/SnapEase/.git"

    - name: Print Deployment Success
      run: echo "Deployment successful!"
